language: python
sudo: true
cache:
  - pip
env:
  global:
    - TMPDIR=/tmp
python:
  - '2.7'
before_install:
  - mkdir -p $HOME/bin
  - wget https://github.com/github/git-lfs/releases/download/v1.1.2/git-lfs-linux-amd64-1.1.2.tar.gz
  - tar xvfz git-lfs-linux-amd64-1.1.2.tar.gz
  - mv git-lfs-1.1.2/git-lfs $HOME/bin/git-lfs
  - export PATH=$PATH:$HOME/bin/
install:
  - pip install -r requirements-dev.txt
script:
  - tox
after_success:
  - codecov
deploy:
  provider: pypi
  user: sammous
  password:
    secure: ujtXZobhqqAgUs3Q6V1p5nvT2P6Jyfh7cXEiwJoofOcji/0NDihkC2VLLAEmBDJmeyG2dUQcc6t7pSlG5IXL8j0iQY1esULhPHIgOE5USRgYOk0HLIGgbBUuaX6lgnYm2xSLEPenP8veb1oGidzoGo2rA1tMhDi7hMeYgt3E3NqoF/Vb6Erp9cgwsVQ6HCWRic6fXA0DctgSUOODNQ/7rDbztmc9OG8MJGS1JaSc4kAtYdbU5Hicrnd254eYe5II3V34HUUuLxNaFkg1qDgvd4uBQemQDSPJIPXiFogtt5smeLsTxUXODEC9oqd/9RwgXNFqxhlcC5sAVrlJ2WU9MUtJv7I4/uLAtp6OfxT0X24jNSq85bjeSfM+irSE4k0JJ+QEHsLmbMWEoyZ/IXqY0kdSbzVGG/HirYqM4vzKLqC5GhG1AeoaMu5FCh+MChdCqmI1xL7luFyfsgkHO7LxGPSMMxc9U20cDEp7Hleh1Z754jmfcxYoCOlwU92irEFlgBZeVKMAq2SgQC2gBFoARC07brxZK1Ac8wuHpAw9CedWUCC3uNX8f7MPmcI/U4tVWqQvoT9aSfb218mL1wbCbSFJymNEao4zq1zOteLs9rX8y0/90WHvfU8RhVSlwIzRs5oX3euFCdaQPIciOfc14ywHPBhBHiu+m2N+6qvyYQ8=
  on:
    tags: true
    branch: master
