language: python
cache: pip
sudo: true
python:
  - "2.7"
install:
  - pip install -r requirements-dev.txt
before_script:
  - python -m spacy download fr
script:
  - "py.test --cov=./"
after_success:
  - codecov
deploy:
  provider: pypi
  user: sammous
  password:
    secure:
      "Kv8zWpk43xBVzxjI5Pn3iMFrK9uT8gc3LVkU5dukszoCZCLqWkVivR2TrI/EBWK1P4BfwcTV5E/
      jVXDhoS5uR1aztk3krNcRBBNbZoUfy9wv2LhvtCZ693BF8j3DS6GVu0PDSbHUOO3mHSaGZ3Gh38P
      GNdMnD918XB3EWelCV1gB5gr5USCAY3pkhiz+LN0OwTb6YGQzU6bvy4aNEAx+g4TJaSMXxOhCdMd
      V5rvkINx7URWXGlu9GLdthGFy1j7YgnGkqu382dAklovujQIxutMrZmfEgObSPFnSiNeSU3siKVf
      fgbU+FesuO8sOWxpIYQZJsWtH5nYfWVi4XuoHRj6e1KsyngBNDE3nHJqKlOOds50I870aHNCSv4r
      bDu1vCllIjRQ8c4sbkh64lmHZAOn6wODTVJi7cex4m38HtoikTuTRBYDAqZ9GFvQ5a2p3Q025Hd2
      0yPYlJfUKdOcnF7eaCZi00bofpeEYgtfq+hR7VcfKiPa4nHlsx5NNvuycOaOAECOsL2CUV32ue8/
      cJDDjIlx4eTIRYR2+Xrof6HKJm2c8ei8DL40+13dzI+V1YqN8wI="
  on:
    branch: master
