codecov:
  branch: master
  bot: null

coverage:
  precision: 2
  round: up
  range: "50...90 "
  target: 70

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  branches: null
  behavior: default

ignore:
  "setup.py"
